DROP TABLE customer;
CREATE TABLE customer (
  cif         NUMBER(10)
, name        VARCHAR2(255) DEFAULT NULL
, branch_open VARCHAR2(255) DEFAULT NULL
, birth_date  VARCHAR2(255) DEFAULT NULL
, mother_name VARCHAR2(255) DEFAULT NULL
, address     VARCHAR2(255) DEFAULT NULL
, id_no       VARCHAR2(255) DEFAULT NULL
, phone_no    VARCHAR2(255) DEFAULT NULL
, mobile_no   VARCHAR2(255) DEFAULT NULL
, email       VARCHAR2(255) DEFAULT NULL
);
EXIT
